/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rajeev Yadav
 */
public class convertion extends javax.swing.JFrame {

    /**
     * Creates new form convertion
     */
    public convertion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Currency convert ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 300, 330, 80);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-query-inner-join-right-96.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(90, 190, 110, 90);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-go-back-40.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(210, 0, 50, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Convert :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 390, 130, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Amount :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 330, 130, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Euro", "US Dollar", "British Poubd", "Indian Rupee", "Singapur Dollar" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(140, 180, 140, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("To :");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 180, 130, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(140, 330, 160, 40);

        jButton1.setBackground(java.awt.SystemColor.textHighlight);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(100, 480, 160, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(140, 390, 160, 30);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(140, 420, 160, 2);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("From :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 250, 130, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Singapur Dollar", "Euro", "US Dollar", "British Poubd", "Indian Rupee", " " }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(140, 250, 140, 40);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3);
        jPanel3.setBounds(260, 0, 50, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(652, 624));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Dasbord d=new Dasbord();
        d.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jPanel4.setBackground(java.awt.Color.RED);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jPanel4.setBackground(java.awt.Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
jPanel3.setBackground(java.awt.Color.red);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
jPanel3.setBackground(java.awt.Color.WHITE);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
this.setVisible(false);
dispose();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String x= jComboBox1.getSelectedItem().toString();
String y= jComboBox2.getSelectedItem().toString();
double a= Float.parseFloat(jTextField2.getText());
if(x.equals("Euro") && y.equals("Singapur Dollar"))
{
    a=a*1.53d;
    jLabel9.setText(String.valueOf(a)+"SD");
}
if(x.equals("Euro") && y.equals("Euro"))
{
   
    jLabel9.setText(String.valueOf(a)+"EU");
}
if(x.equals("Euro") && y.equals("US Dollar"))
{
   a=a*1.125d;
    jLabel9.setText(String.valueOf(a)+"USD");
}
if(x.equals("Euro") && y.equals("British Poubd"))
{
   a=a*0.898426d;
    jLabel9.setText(String.valueOf(a)+"BP");
}
if(x.equals("Euro") && y.equals("Indian Rupee"))
{
   a=a*77.338426d;
    jLabel9.setText(String.valueOf(a)+"RS");
}
if(x.equals("US Dollar") && y.equals("Singapur Dollar"))
{
   a=a*1.360431d;
    jLabel9.setText(String.valueOf(a)+"SD");
}
if(x.equals("US Dollar") && y.equals("Euro"))
{
   a=a*0.891382d;
    jLabel9.setText(String.valueOf(a)+"EU");
}
if(x.equals("US Dollar") && y.equals("British Poubd"))
{
   a=a*0.801010d;
    jLabel9.setText(String.valueOf(a)+"BP");
}
if(x.equals("US Dollar") && y.equals("US Dollar"))
{
   
    jLabel9.setText(String.valueOf(a)+"USD");
}

if(x.equals("US Dollar") && y.equals("Indian Rupee"))
{
   a=a*68.889434d;
    jLabel9.setText(String.valueOf(a)+"RS");
}
if(x.equals("British Poubd") && y.equals("Singapur Dollar"))
{
   a=a*1.69873d;
    jLabel9.setText(String.valueOf(a)+"SD");
}
if(x.equals("British Poubd") && y.equals("Euro"))
{
   a=a*1.11294d;
    jLabel9.setText(String.valueOf(a)+"EU");
}
if(x.equals("British Poubd") && y.equals("US Dollar"))
{
   a=a*1.24835d;
    jLabel9.setText(String.valueOf(a)+"USD");
}
if(x.equals("British Poubd") && y.equals("British Poubd"))
{
   
    jLabel9.setText(String.valueOf(a)+"BP");
}
if(x.equals("British Poubd") && y.equals("Indian Rupee"))
{
   a=a*85.9805d;
    jLabel9.setText(String.valueOf(a)+"RS");
}
if(x.equals("Indian Rupee") && y.equals("Singapur Dollar"))
{
   a=a*0.0197635d;
    jLabel9.setText(String.valueOf(a)+"SD");
}
if(x.equals("Indian Rupee") && y.equals("Euro"))
{
   a=a*0.0129474d;
    jLabel9.setText(String.valueOf(a)+"EU");
}

if(x.equals("Indian Rupee") && y.equals("US Dollar"))
{
   a=a*0.0145199d;
    jLabel9.setText(String.valueOf(a)+"USD");
}
if(x.equals("Indian Rupee") && y.equals("British Poubd"))
{
   a=a*0.0116326d;
    jLabel9.setText(String.valueOf(a)+"BP");
}
if(x.equals("Indian Rupee") && y.equals("Indian Rupee"))
{
   
    jLabel9.setText(String.valueOf(a)+"RS");
}
if(x.equals("Singapur Dollar") && y.equals("Singapur Dollar"))
{
   
    jLabel9.setText(String.valueOf(a)+"SD");
}
if(x.equals("Singapur Dollar") && y.equals("Euro"))
{
   a=a*0.655166d;
    jLabel9.setText(String.valueOf(a)+"EU");
}
if(x.equals("Singapur Dollar") && y.equals("US Dollar"))
{
   a=a*0.734741d;
    jLabel9.setText(String.valueOf(a)+"USD");
}
if(x.equals("Singapur Dollar") && y.equals("British Poubd"))
{
   a=a*0.588596d;
    jLabel9.setText(String.valueOf(a)+"BP");
}
if(x.equals("Singapur Dollar") && y.equals("Indian Rupee"))
{
   a=a*50.6127d;
    jLabel9.setText(String.valueOf(a)+"RS");
}

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convertion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convertion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
